name: Deploy to GitHub Pages

permissions:
    contents: write
    pull-requests: write 
    issues: read
    packages: none

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install  # Modify this if you're using a different package manager

    - name: Build
      run: npm run build  # Adjust the build script according to your project setup

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist # Change this to the build output directory